language: php
php:
  - 5.3
  - 5.4
  - 5.5
before_script:
  - composer install --dev --prefer-source
script:
  - php vendor/behat/behat/bin/behat
  - php vendor/phpspec/phpspec/scripts/phpspec.php spec