//curl -u username:password http://cyclos.proudleo.com:8080/cyclos/rest/accounts/info
[{"account":{"id":17,
			 "type":{"id":10,
				 	 "name":"Business Time Account",
				 	 "currency":{"id":2,
				 		  		 "symbol":"hrs",
				 		  		 "name":"Hours of Time"}},
			"default":false},
  "status":{"balance":4.000000,
	 	   "formattedBalance":"4.00 hrs",
	 	   "availableBalance":4.000000,
	 	   "formattedAvailableBalance":"4.00 hrs",
	 	   "reservedAmount":0.000000,
	 	   "formattedReservedAmount":"0.00 hrs",
	 	   "creditLimit":0.000000,
	 	   "formattedCreditLimit":"0.00 hrs"}},
 {"account":{"id":5,
			  "type":{"id":5,
					  "name":"Member account",
					  "currency":{"id":1,
						  		  "symbol":"units",
						  		  "name":"Units"}},
		      "default":false},
  "status":{"balance":0,
	  		"formattedBalance":"0.00 units",
	  		"availableBalance":0.000000,
	  		"formattedAvailableBalance":"0.00 units",
	  		"reservedAmount":0,
	  		"formattedReservedAmount":"0.00 units",
	  		"creditLimit":0.000000,
	  		"formattedCreditLimit":"0.00 units"}},
{"account":{"id":14,"type":{"id":9,"name":"Personal Bulkly Bucks","currency":{"id":6,"symbol":"bb","name":"Bulkly Bucks"}},"default":false},"status":{"balance":0,"formattedBalance":"0.00 bb","availableBalance":0.000000,"formattedAvailableBalance":"0.00 bb","reservedAmount":0,"formattedReservedAmount":"0.00 bb","creditLimit":0.000000,"formattedCreditLimit":"0.00 bb"}},{"account":{"id":11,"type":{"id":8,"name":"Personal Community Way","currency":{"id":3,"symbol":"cw","name":"Community Way"}},"default":false},"status":{"balance":0,"formattedBalance":"0.00 cw","availableBalance":0.000000,"formattedAvailableBalance":"0.00 cw","reservedAmount":0,"formattedReservedAmount":"0.00 cw","creditLimit":0.000000,"formattedCreditLimit":"0.00 cw"}},{"account":{"id":8,"type":{"id":7,"name":"Personal Time Account","currency":{"id":2,"symbol":"hrs","name":"Hours of Time"}},"default":true},"status":{"balance":0,"formattedBalance":"0.00 hrs","availableBalance":0.000000,"formattedAvailableBalance":"0.00 hrs","reservedAmount":0,"formattedReservedAmount":"0.00 hrs","creditLimit":0.000000,"formattedCreditLimit":"0.00 hrs"}}]